language: python
python: '2.7'
install:
- pip install -r requirements.txt
addons:
  sauce_connect: true
before_script:
- cd public
- python -m SimpleHTTPServer 8080 2>&1 > /dev/null &
- cd ..
script:
- nosetests
after_success:
  - npm install -g surge
deploy:
  provider: script
  script: surge public
  on:
    repo: yoavram/Plato
    branch: master
  skip_cleanup: true
