language: python

python: "2.7"

install: 
  - pip install -r requirements.txt

addons: 
  sauce_connect: true

before_script:
  - cd public
  - python -m SimpleHTTPServer 8080 2>&1 > /dev/null &
  - cd ..

script: 
  - nosetests